Add API for obtaining simulation reports via workflow id and print job id
amychisholm03/hp-capstone-2025-backend pull request #13
Opened 2024-10-25 20:59 UTC by LukeErdy

2024-10-25 21:05 UTC, CadeTormanen submitted a review, later dismissed
LGTM!

2024-10-26 22:26 UTC, amychisholm03 requested changes
Please create a unit test in `server.test.js` that verifies that `getsSmluationReport` works as intended.

2024-10-28 20:00 UTC, amychisholm03 commented on test/unit/server.test.js
I'm not seeing any change?

2024-10-29 20:41 UTC, amychisholm03 approved these changes
CI is working (your test is passing) and merge conflicts are resolved. LGTM

2024-10-29 20:46 UTC, CadeTormanen approved these changes
Looks Goated

2024-10-29 20:46 UTC, merged