feat: Add /getWorkflowStepList GET API
amychisholm03/hp-capstone-2025-backend pull request #21
Opened 2024-11-06 23:54 UTC by LukeErdy

2024-11-07 03:10 UTC, Caleb-Biggs requested changes, later dismissed
Add tests

2024-11-07 16:13 UTC, amychisholm03 requested changes

2024-11-07 16:13 UTC, amychisholm03 commented on test/integration/server.test.js
> +    console.log("Workflow steps: ", payloadList);
Could we maybe assert that `payloadList` is at least non-null and contains some steps (don't necessarily need to verify each individual step)?

2024-11-09 18:11 UTC, amychisholm03 approved these changes

2024-11-09 21:50 UTC, Gabrielle-Barling approved these changes
lgtm

2024-11-09 21:51 UTC, merged