feat: Added /getPrintJob and fixed /query
amychisholm03/hp-capstone-2025-backend pull request #22
Opened 2024-11-07 03:01 UTC by Caleb-Biggs

2024-11-07 16:19 UTC, amychisholm03 requested changes

2024-11-07 16:19 UTC, amychisholm03 commented on README.md
> +curl -G -X GET http://54.200.253.84:80/query --data-urlencode "CollectionName=PrintJob" --data-urlencode "Query={\"Title\":\"PrintJob 1\"}"
Please use domain name (`http://api.wsuv-hp-capstone.com/`) instead of IP

2024-11-07 16:19 UTC, amychisholm03 commented on server.js
> +    reply.code(code).send(message);
Maybe have this (line 60) in a `finally` block?

2024-11-07 16:19 UTC, amychisholm03 commented on test/integration/server.test.js
> +    console.log("Query Results:", JSON.parse(response.payload));
At least assert `response.payload` contains something

2024-11-07 16:19 UTC, amychisholm03 commented on server.js
> +    const PrintJob = request.query.PrintJobName;
Why `PrintJobName` instead of `Title` like the other APIs?

2024-11-07 16:19 UTC, amychisholm03 commented on server.js
> +  if(process.argv.length > 2) start("0.0.0.0", process.argv[2]);
Ah nice touch

2024-11-09 18:11 UTC, amychisholm03 approved these changes, later dismissed

2024-11-13 00:50 UTC, CadeTormanen approved these changes
looks great

2024-11-13 00:54 UTC, amychisholm03 approved these changes
ship it

2024-11-13 00:54 UTC, merged